# The live logo is not an image: abclondonproperty.co.uk sets "ABC LONDON PROPERTY GROUP" as live text in Bitter 700
# (GoDaddy font pack "bitter", #FF6900, two centred lines "ABC LONDON" / "PROPERTY GROUP"). This script turns that
# lock-up into vector outlines from the self-hosted Bitter variable font (instanced at weight 700), so the logo is a
# real SVG with every letter a separate path the preloader can animate. Writes lib/logo.ts.
# Usage: python3 scripts/logo.py
import json
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

font = TTFont("public/fonts/bitter-latin-wght-normal.woff2")
font = instantiateVariableFont(font, {"wght": 700})
gs = font.getGlyphSet()
cmap = font.getBestCmap()
upm = font["head"].unitsPerEm
hmtx = font["hmtx"]
cap = font["OS/2"].sCapHeight

LINES = ["ABC LONDON", "PROPERTY GROUP"]
SIZE = 100            # px per em in the SVG's own units
LEADING = 1.12        # line pitch in em: the live h3 runs at line-height 1.1 to 1.2
scale = SIZE / upm

def line_width(text):
    return sum(hmtx[cmap[ord(c)]][0] for c in text) * scale

widths = [line_width(t) for t in LINES]
W = max(widths)
cap_px = cap * scale
pitch = SIZE * LEADING
parts = []
for li, text in enumerate(LINES):
    x = (W - widths[li]) / 2
    baseline = cap_px + li * pitch
    word = 0
    for c in text:
        g = cmap[ord(c)]
        adv = hmtx[g][0] * scale
        if c == " ":
            word += 1; x += adv; continue
        pen = SVGPathPen(gs, ntos=lambda v: f"{v:.1f}".rstrip("0").rstrip("."))
        gs[g].draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
        bp = BoundsPen(gs); gs[g].draw(TransformPen(bp, (scale, 0, 0, -scale, x, baseline)))
        parts.append({"ch": c, "line": li, "word": f"{li}-{word}", "d": pen.getCommands(), "box": [round(v, 1) for v in bp.bounds]})
        x += adv

H = cap_px + pitch
out = {"width": round(W, 1), "height": round(H, 1), "capHeight": round(cap_px, 1), "pitch": round(pitch, 1), "parts": parts}
with open("lib/logo.ts", "w") as f:
    f.write("// Generated by scripts/logo.py from Bitter 700 (the live logo's typeface). Do not edit by hand.\n")
    f.write("// Each part is one letter; `word` is line-word (0-0 ABC, 0-1 LONDON, 1-0 PROPERTY, 1-1 GROUP).\n")
    f.write("export const logo = " + json.dumps(out, indent=1) + " as const;\n")
print(W, H, len(parts))

# Favicon: the three initials, orange on Ink, from the same outlines.
abc = [p for p in parts if p["word"] == "0-0"]
x0 = min(p["box"][0] for p in abc); x1 = max(p["box"][2] for p in abc)
y0 = min(p["box"][1] for p in abc); y1 = max(p["box"][3] for p in abc)
s = 48 / (x1 - x0); tx = 8 - x0 * s; ty = 32 - (y0 + y1) / 2 * s
paths = "".join(f'<path d="{p["d"]}"/>' for p in abc)
with open("app/icon.svg", "w") as f:
    f.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="#161616"/>'
            f'<g fill="#FF6900" transform="translate({tx:.2f} {ty:.2f}) scale({s:.4f})">{paths}</g></svg>')
